Repository Lotte-Niddles/5so4so, pull requests merged in 2022-07, with the labels that each got.

#19 Feat: 관리자 상품 등록 기능 구현 #6
  pom.xml
  src/main/java/com/needle/FsoFso/admin/controller/SellerProductController.java
  src/main/java/com/needle/FsoFso/admin/dao/SellerProductDao.java
  src/main/java/com/needle/FsoFso/admin/dao/SellerProductDaoImpl.java
  src/main/java/com/needle/FsoFso/admin/dto/SellerProductDto.java
  src/main/java/com/needle/FsoFso/admin/service/SellerProductService.java
  src/main/java/com/needle/FsoFso/admin/service/SellerProductServiceImpl.java
  src/main/java/com/needle/FsoFso/admin/util/FTPUtil.java
  src/main/java/resources/mybatis-config.xml
  src/main/java/resources/sqls/SellerProduct.xml
  src/main/webapp/WEB-INF/spring/applicationContext.xml
  src/main/webapp/WEB-INF/spring/pds-context.xml
  src/main/webapp/WEB-INF/spring/servlet-context.xml
  src/main/webapp/WEB-INF/views/admin/addProduct.jsp
  src/main/webapp/WEB-INF/web.xml
Labels: ⭐️기능

#21 Fix: 로그인 시 성별이 저장되지 않는 문제 해결
  pom.xml
  src/main/java/com/needle/FsoFso/member/kakao/dto/KakaoUserInfo.java
  src/main/java/com/needle/FsoFso/member/service/Member.java
  src/main/resources/mybatis-config.xml
  src/main/resources/sqls/Member.xml
  src/main/resources/sqls/SellerProduct.xml
  src/main/webapp/WEB-INF/applicationContext.xml
  src/main/webapp/WEB-INF/spring-context.xml
Labels: 🐞버그, ⭐️기능

#23 Feat: 관리자페이지 초안 업로드 #4
  .gitignore
  src/main/java/com/needle/FsoFso/admin/controller/AdminController.java
  src/main/java/com/needle/FsoFso/admin/dao/AdminDao.java
  src/main/java/com/needle/FsoFso/admin/dao/AdminDaoImpl.java
  src/main/java/com/needle/FsoFso/admin/dto/AdminMainRequestDto.java
  src/main/java/com/needle/FsoFso/admin/dto/AdminMemberDto.java
  src/main/java/com/needle/FsoFso/admin/dto/AdminMemberListRequestDto.java
  src/main/java/com/needle/FsoFso/admin/dto/AdminProductDto.java
  src/main/java/com/needle/FsoFso/admin/dto/AdminProductListRequestDto.java
  src/main/java/com/needle/FsoFso/admin/dto/DailyDetailDto.java
  src/main/java/com/needle/FsoFso/admin/service/AdminService.java
  src/main/java/com/needle/FsoFso/admin/service/AdminServiceImpl.java
  src/main/java/sqls/admin.xml
  src/main/webapp/WEB-INF/views/admin/adminMain.jsp
  src/main/webapp/WEB-INF/views/admin/adminMemberList.jsp
  src/main/webapp/WEB-INF/views/admin/adminProductList.jsp
  src/main/webapp/WEB-INF/views/admin/adminTopInc.jsp
  src/main/webapp/WEB-INF/views/layouts-tiles.jsp
  src/main/webapp/WEB-INF/views/layouts.xml
  src/main/webapp/css/admin/adminMain.css
Labels: ⭐️기능

#22 Feat: 메인페이지 상품 차트 및 페이징
  src/main/java/com/needle/FsoFso/product/controller/ProductController.java
  src/main/java/com/needle/FsoFso/product/dao/ProductDao.java
  src/main/java/com/needle/FsoFso/product/dao/ProductDaoImpl.java
  src/main/java/com/needle/FsoFso/product/dto/ProductDto.java
  src/main/java/com/needle/FsoFso/product/services/ProductService.java
  src/main/java/com/needle/FsoFso/product/services/ProductServiceImpl.java
  src/main/java/com/needle/FsoFso/search/controller/SearchController.java
  src/main/java/com/needle/FsoFso/search/dto/SearchDto.java
  src/main/java/properties/jdbc.properties
  src/main/java/sqls/product.xml
  src/main/java/sqls/search.xml
  src/main/webapp/WEB-INF/spring/applicationContext.xml
  src/main/webapp/WEB-INF/spring/servlet-context.xml
  src/main/webapp/WEB-INF/views/commons/bottom_inc.jsp
  src/main/webapp/WEB-INF/views/commons/header.jsp
  src/main/webapp/WEB-INF/views/commons/top_inc.jsp
  src/main/webapp/WEB-INF/views/commons/top_menu.jsp
  src/main/webapp/WEB-INF/views/layouts-tiles.jsp
  src/main/webapp/WEB-INF/views/layouts.xml
  src/main/webapp/WEB-INF/views/main.jsp
  src/main/webapp/WEB-INF/views/search/searchList.jsp
  src/main/webapp/WEB-INF/web.xml
  src/main/webapp/css/common/bottom_inc.css
  src/main/webapp/css/common/top_inc.css
  src/main/webapp/css/product/main.css
  src/main/webapp/images/cart.png
  src/main/webapp/images/favicon.png
  src/main/webapp/images/github.png
  src/main/webapp/images/glass.png
  src/main/webapp/images/logo.png
  src/main/webapp/images/notion.png
  src/main/webapp/index.jsp
Labels: ⭐️기능

#24 Feat: 검색기능 구현
  .gitignore
  src/main/java/com/needle/FsoFso/search/controller/SearchController.java
  src/main/java/com/needle/FsoFso/search/dao/SearchDao.java
  src/main/java/com/needle/FsoFso/search/dao/SearchDaoImpl.java
  src/main/java/com/needle/FsoFso/search/dto/SearchParamDto.java
  src/main/java/com/needle/FsoFso/search/service/SearchService.java
  src/main/java/com/needle/FsoFso/search/service/SearchServiceImpl.java
  src/main/resources/sqls/search.xml
  src/main/webapp/WEB-INF/views/commons/top_inc.jsp
  src/main/webapp/WEB-INF/views/main.jsp
  src/main/webapp/WEB-INF/views/search/searchList.jsp
Labels: ⚒️리팩토링

#26 Feat: 메인화면 슬라이드, hover 확대효과, to-top버튼, 폰트 추가
  src/main/java/com/needle/FsoFso/admin/dto/AdminProductListRequestDto.java
  src/main/webapp/WEB-INF/views/commons/bottom_inc.jsp
  src/main/webapp/WEB-INF/views/commons/header.jsp
  src/main/webapp/WEB-INF/views/commons/top_inc.jsp
  src/main/webapp/WEB-INF/views/layouts-tiles.jsp
  src/main/webapp/WEB-INF/views/main.jsp
  src/main/webapp/css/common/bottom_inc.css
  src/main/webapp/css/font/Jalpullineun Medium.ttf
  src/main/webapp/css/font/JalpullineunOTF Medium.otf
  src/main/webapp/css/product/main.css
  src/main/webapp/images/product/slide1.png
  src/main/webapp/images/product/slide2.png
  src/main/webapp/images/product/slide3.png
  src/main/webapp/images/product/slide4.png
  src/main/webapp/images/product/slide5.png
Labels: ⭐️기능

#28 Refector: 관리자 페이지 수정 #4
  src/main/java/com/needle/FsoFso/admin/controller/AdminController.java
  src/main/java/com/needle/FsoFso/admin/dao/AdminDao.java
  src/main/java/com/needle/FsoFso/admin/dao/AdminDaoImpl.java
  src/main/java/com/needle/FsoFso/admin/dao/SellerProductDao.java
  src/main/java/com/needle/FsoFso/admin/dto/AdminMainRequestDto.java
  src/main/java/com/needle/FsoFso/admin/dto/AdminMemberDto.java
  src/main/java/com/needle/FsoFso/admin/dto/AdminMemberListRequestDto.java
  src/main/java/com/needle/FsoFso/admin/dto/AdminProductDto.java
  src/main/java/com/needle/FsoFso/admin/dto/AdminProductListRequestDto.java
  src/main/java/com/needle/FsoFso/admin/dto/DailyDetailDto.java
  src/main/java/com/needle/FsoFso/admin/service/AdminService.java
  src/main/java/com/needle/FsoFso/admin/service/AdminServiceImpl.java
  src/main/java/com/needle/FsoFso/admin/util/InstantUtil.java
  src/main/resources/sqls/Admin.xml
  src/main/webapp/WEB-INF/views/admin/adminMain.jsp
  src/main/webapp/WEB-INF/views/admin/adminMemberList.jsp
  src/main/webapp/WEB-INF/views/admin/adminProductList.jsp
  src/main/webapp/WEB-INF/views/admin/adminTopInc.jsp
  src/main/webapp/images/admin.png
Labels: ⭐️기능, ⚒️리팩토링

#32 Chore: 불필요한 프로퍼티 파일 제거
  src/main/java/properties/jdbc.properties
Labels: 🤔기타

#37 Fix: 로그아웃 처리 및 메인페이지의 페이지 번호 수정
  src/main/webapp/WEB-INF/views/admin/adminTopInc.jsp
  src/main/webapp/WEB-INF/views/layouts-tiles.jsp
  src/main/webapp/WEB-INF/views/main.jsp
  src/main/webapp/WEB-INF/views/search/searchList.jsp
  src/main/webapp/css/product/main.css
Labels: 🐞버그, ⚒️리팩토링

#40 Fix: 좀비 admin.xml 수정
  src/main/resources/sqls/admin.xml
Labels: 🐞버그

#42 Feat: 리뷰 작성 및 조회 기능 구현
  src/main/java/com/needle/FsoFso/admin/dao/AdminDaoImpl.java
  src/main/java/com/needle/FsoFso/member/dao/MemberDao.java
  src/main/java/com/needle/FsoFso/member/service/MemberService.java
  src/main/java/com/needle/FsoFso/product/controller/ProductController.java
  src/main/java/com/needle/FsoFso/product/dao/ProductDao.java
  src/main/java/com/needle/FsoFso/product/dao/ProductDaoImpl.java
  src/main/java/com/needle/FsoFso/product/service/ProductService.java
  src/main/java/com/needle/FsoFso/product/service/ProductServiceImpl.java
  src/main/java/com/needle/FsoFso/review/controller/ReviewController.java
  src/main/java/com/needle/FsoFso/review/dao/ReviewDao.java
  src/main/java/com/needle/FsoFso/review/dao/ReviewDaoImpl.java
  src/main/java/com/needle/FsoFso/review/dto/MemberProductDto.java
  src/main/java/com/needle/FsoFso/review/dto/ReviewDto.java
  src/main/java/com/needle/FsoFso/review/service/ReviewService.java
  src/main/java/com/needle/FsoFso/review/service/ReviewServiceImpl.java
  src/main/resources/sqls/product.xml
  src/main/resources/sqls/review.xml
  src/main/webapp/WEB-INF/views/layouts.xml
  src/main/webapp/WEB-INF/views/product/productDetail.jsp
  src/main/webapp/WEB-INF/views/review/addReview.jsp
Labels: ⭐️기능

#43 Refactor: 상품 가격 표시 수정
  src/main/java/com/needle/FsoFso/common/util/CurrencyFormatter.java
  src/main/webapp/WEB-INF/views/main.jsp
Labels: ⭐️기능, ⚒️리팩토링

#44 Refactor: 검색 페이지 css적용 및 top버튼 추가
  src/main/webapp/WEB-INF/views/commons/top_inc.jsp
  src/main/webapp/WEB-INF/views/search/searchList.jsp
Labels: ⚒️리팩토링

#46 Refactor: 메인페이지에서 페이지 번호 위치 문제
  src/main/webapp/css/product/main.css
Labels: ⚒️리팩토링

#51 Refactor: 관리자 상품목록 검색 추가
  src/main/java/com/needle/FsoFso/admin/controller/AdminController.java
  src/main/java/com/needle/FsoFso/admin/dao/AdminDao.java
  src/main/java/com/needle/FsoFso/admin/dao/AdminDaoImpl.java
  src/main/java/com/needle/FsoFso/admin/dto/AdminOrderDto.java
  src/main/java/com/needle/FsoFso/admin/dto/AdminOrderListRequestDto.java
  src/main/java/com/needle/FsoFso/admin/dto/AdminOrderProductDto.java
  src/main/java/com/needle/FsoFso/admin/dto/AdminOrderProductListRequestDto.java
  src/main/java/com/needle/FsoFso/admin/dto/AdminProductDto.java
  src/main/java/com/needle/FsoFso/admin/service/AdminService.java
  src/main/java/com/needle/FsoFso/admin/service/AdminServiceImpl.java
  src/main/resources/sqls/Admin.xml
  src/main/webapp/WEB-INF/views/admin/adminOrderList.jsp
  src/main/webapp/WEB-INF/views/admin/adminOrderProductList.jsp
  src/main/webapp/WEB-INF/views/admin/adminProductList.jsp
  src/main/webapp/WEB-INF/views/admin/adminTopInc.jsp
  src/main/webapp/WEB-INF/views/commons/top_inc.jsp
  src/main/webapp/WEB-INF/views/layouts.xml
  src/main/webapp/WEB-INF/views/search/searchList.jsp
Labels: ⭐️기능, ⚒️리팩토링

#50 Feature: 상품 상세페이지 리뷰 페이지 스타일, 슬라이드 이미지 변경
  src/main/java/com/needle/FsoFso/admin/util/InstantUtil.java
  src/main/resources/sqls/product.xml
  src/main/webapp/WEB-INF/views/admin/addProduct.jsp
  src/main/webapp/WEB-INF/views/main.jsp
  src/main/webapp/WEB-INF/views/product/productDetail.jsp
  src/main/webapp/WEB-INF/views/review/addReview.jsp
  src/main/webapp/css/product/main.css
  src/main/webapp/images/product/slide1.png
  src/main/webapp/images/product/slide2.png
  src/main/webapp/images/product/slide3.png
  src/main/webapp/images/product/slide4.png
  src/main/webapp/images/product/slide5.png
Labels: ⭐️기능

#52 Feat:결제 로직 구현
  src/main/java/com/needle/FsoFso/order/controller/OrderController.java
  src/main/java/com/needle/FsoFso/order/domain/Order.java
  src/main/java/com/needle/FsoFso/order/dto/Order/OrderSearchCond.java
  src/main/java/com/needle/FsoFso/order/dto/Order/OrderUpdateDto.java
  src/main/java/com/needle/FsoFso/order/dto/OrderProduct/OrderProduct.java
  src/main/java/com/needle/FsoFso/order/dto/Shop/DisplayShopDto.java
  src/main/java/com/needle/FsoFso/order/dto/Shop/ShopDto.java
  src/main/java/com/needle/FsoFso/order/repository/OrderProductRepository.java
  src/main/java/com/needle/FsoFso/order/repository/OrderRepository.java
  src/main/java/com/needle/FsoFso/order/repository/ProductsRepository.java
  src/main/java/com/needle/FsoFso/order/repository/ShopRepository.java
  src/main/java/com/needle/FsoFso/order/repository/mybatis/OrderMapper.java
  src/main/java/com/needle/FsoFso/order/repository/mybatis/OrderProductMapper.java
  src/main/java/com/needle/FsoFso/order/repository/mybatis/ProductsMapper.java
  src/main/java/com/needle/FsoFso/order/repository/mybatis/ShopMapper.java
  src/main/java/com/needle/FsoFso/order/service/OrderService.java
  src/main/java/com/needle/FsoFso/order/service/ShopService.java
  src/main/resources/sqls/OrderMapper.xml
  src/main/resources/sqls/OrderProductMapper.xml
  src/main/resources/sqls/ProductMapper.xml
  src/main/resources/sqls/ShopMapper.xml
  src/main/webapp/WEB-INF/spring/applicationContext.xml
  src/main/webapp/WEB-INF/views/order/order.jsp
Labels: ⭐️기능

#54 Fix: 검색창 위치 수정, 슬라이드 사진변경
  src/main/java/com/needle/FsoFso/admin/controller/AdminController.java
  src/main/java/com/needle/FsoFso/admin/dao/AdminDao.java
  src/main/java/com/needle/FsoFso/admin/dao/AdminDaoImpl.java
  src/main/java/com/needle/FsoFso/admin/service/AdminService.java
  src/main/java/com/needle/FsoFso/admin/service/AdminServiceImpl.java
  src/main/resources/sqls/Admin.xml
  src/main/webapp/WEB-INF/views/admin/adminMemberList.jsp
  src/main/webapp/WEB-INF/views/admin/adminOrderList.jsp
  src/main/webapp/WEB-INF/views/admin/adminProductList.jsp
  src/main/webapp/images/product/slide1.png
  src/main/webapp/images/product/slide4.png
Labels: ⭐️기능

#55 Refactor: 관리자 주문 관리 검색 추가
  src/main/java/com/needle/FsoFso/admin/controller/AdminController.java
  src/main/java/com/needle/FsoFso/admin/dao/AdminDao.java
  src/main/java/com/needle/FsoFso/admin/dao/AdminDaoImpl.java
  src/main/java/com/needle/FsoFso/admin/service/AdminService.java
  src/main/java/com/needle/FsoFso/admin/service/AdminServiceImpl.java
  src/main/resources/sqls/Admin.xml
  src/main/webapp/WEB-INF/views/admin/adminMemberList.jsp
  src/main/webapp/WEB-INF/views/admin/adminOrderList.jsp
  src/main/webapp/WEB-INF/views/admin/adminProductList.jsp
  src/main/webapp/WEB-INF/views/commons/top_inc.jsp
Labels: ⚒️리팩토링

#60 Fix: layouts.xml adminOrder 페이지 안뜨는 오류 수정
  src/main/webapp/WEB-INF/views/layouts.xml
Labels: 🐞버그

#58 Feat: 결제 Seesion 기능 및 Dto 필드 값 추가
  src/main/java/com/needle/FsoFso/order/controller/OrderController.java
  src/main/java/com/needle/FsoFso/order/dto/Order/OrderSuccessDto.java
  src/main/java/com/needle/FsoFso/order/dto/Shop/DisplayShopDto.java
  src/main/resources/sqls/ShopMapper.xml
Labels: ⭐️기능

#59 Feat: 마이페이지 구현
  src/main/java/com/needle/FsoFso/member/controller/MemberController.java
  src/main/java/com/needle/FsoFso/member/controller/dto/NicknameRequest.java
  src/main/java/com/needle/FsoFso/member/dao/MemberDao.java
  src/main/java/com/needle/FsoFso/member/service/Member.java
  src/main/java/com/needle/FsoFso/member/service/MemberService.java
  src/main/java/com/needle/FsoFso/order/dto/OrderProductResponse.java
  src/main/java/com/needle/FsoFso/order/dto/OrderResponse.java
  src/main/java/com/needle/FsoFso/order/repository/OrderRepository.java
  src/main/java/com/needle/FsoFso/order/repository/mybatis/OrderMapper.java
  src/main/java/com/needle/FsoFso/order/service/OrderService.java
  src/main/java/com/needle/FsoFso/product/controller/ProductController.java
  src/main/java/com/needle/FsoFso/review/controller/ReviewController.java
  src/main/java/com/needle/FsoFso/review/dao/ReviewDao.java
  src/main/java/com/needle/FsoFso/review/dao/ReviewDaoImpl.java
  src/main/java/com/needle/FsoFso/review/dto/Review.java
  src/main/java/com/needle/FsoFso/review/dto/ReviewDto.java
  src/main/java/com/needle/FsoFso/review/service/ReviewService.java
  src/main/java/com/needle/FsoFso/review/service/ReviewServiceImpl.java
  src/main/resources/sqls/Member.xml
  src/main/resources/sqls/OrderMapper.xml
  src/main/resources/sqls/review.xml
  src/main/webapp/WEB-INF/views/commons/top_inc.jsp
  src/main/webapp/WEB-INF/views/layouts.xml
  src/main/webapp/WEB-INF/views/member/mypage.jsp
  src/main/webapp/WEB-INF/views/product/productDetail.jsp
  src/main/webapp/css/member/mypage.css
  src/main/webapp/images/smile.png
Labels: ⭐️기능

#63 Refactor: 검색어 공백제거
  src/main/resources/sqls/search.xml
  src/main/webapp/WEB-INF/views/admin/adminMemberList.jsp
  src/main/webapp/WEB-INF/views/admin/adminOrderList.jsp
  src/main/webapp/WEB-INF/views/admin/adminProductList.jsp
  src/main/webapp/WEB-INF/views/commons/top_inc.jsp
Labels: ⚒️리팩토링

#67 Refactor: 검색영역 포커스및 관리자 목록 쿼리 수정
  src/main/resources/sqls/Admin.xml
  src/main/webapp/WEB-INF/views/admin/adminMemberList.jsp
  src/main/webapp/WEB-INF/views/admin/adminOrderList.jsp
  src/main/webapp/WEB-INF/views/admin/adminProductList.jsp
Labels: ⚒️리팩토링

#71 Feat: 관리자 차트 추가
  src/main/java/com/needle/FsoFso/admin/controller/AdminController.java
  src/main/java/com/needle/FsoFso/admin/dao/AdminDao.java
  src/main/java/com/needle/FsoFso/admin/dao/AdminDaoImpl.java
  src/main/java/com/needle/FsoFso/admin/dto/AgeChartDto.java
  src/main/java/com/needle/FsoFso/admin/dto/GenderChartDto.java
  src/main/java/com/needle/FsoFso/admin/service/AdminService.java
  src/main/java/com/needle/FsoFso/admin/service/AdminServiceImpl.java
  src/main/resources/sqls/Admin.xml
  src/main/webapp/WEB-INF/views/admin/adminMain.jsp
Labels: ⭐️기능

#69 Fix: 장바구니 추가, 리뷰 작성 컨트롤러 수정
  src/main/java/com/needle/FsoFso/product/controller/ProductController.java
  src/main/java/com/needle/FsoFso/review/controller/ReviewController.java
Labels: 🐞버그, ⭐️기능

#73 Feat: 장바구니 삭제 기능 추가
  src/main/java/com/needle/FsoFso/order/controller/OrderController.java
  src/main/java/com/needle/FsoFso/order/dto/Order/OrderSuccessDto.java
  src/main/java/com/needle/FsoFso/order/dto/Shop/ShopDto.java
  src/main/java/com/needle/FsoFso/order/repository/ShopRepository.java
  src/main/java/com/needle/FsoFso/order/repository/mybatis/ShopMapper.java
  src/main/java/com/needle/FsoFso/order/service/OrderService.java
  src/main/java/com/needle/FsoFso/order/service/ShopService.java
  src/main/resources/sqls/ShopMapper.xml
  src/main/webapp/WEB-INF/views/layouts.xml
  src/main/webapp/WEB-INF/views/order/orderSuccess.jsp
Labels: ⭐️기능

#72 Feat: order.jsp 주문하기 버튼 삭제하기 버튼 구현
  src/main/webapp/WEB-INF/views/order/order.jsp
Labels: ⭐️기능

#77 Fix: order.jsp 사소한 오류 수정
  src/main/webapp/WEB-INF/views/order/order.jsp
Labels: 🐞버그

#79 Fix: 리뷰 관련 기능 수정
  src/main/java/com/needle/FsoFso/review/controller/ReviewController.java
  src/main/webapp/WEB-INF/views/product/productDetail.jsp
Labels: 🐞버그

#81 fix: 장바구니 View 삭제 오류 수정
  src/main/java/com/needle/FsoFso/order/controller/OrderController.java
  src/main/webapp/WEB-INF/views/order/order.jsp
Labels: 🐞버그

#83 fix: 장바구니 상품 삭제 시 발생하는 새로고침 오류 해결
  src/main/java/com/needle/FsoFso/order/controller/OrderController.java
  src/main/webapp/WEB-INF/views/order/order.jsp
Labels: 🐞버그

#68 Refactor: 로그인 검증 로직 수정, 404&500 페이지 추가
  src/main/java/com/needle/FsoFso/admin/controller/AdminController.java
  src/main/java/com/needle/FsoFso/admin/controller/SellerProductController.java
  src/main/java/com/needle/FsoFso/common/aop/AdminOnly.java
  src/main/java/com/needle/FsoFso/common/aop/LoginAop.java
  src/main/java/com/needle/FsoFso/common/aop/MemberOnly.java
  src/main/java/com/needle/FsoFso/common/ui/CommonController.java
  src/main/java/com/needle/FsoFso/member/controller/AdminMembers.java
  src/main/java/com/needle/FsoFso/member/controller/MemberController.java
  src/main/java/com/needle/FsoFso/member/service/MemberService.java
  src/main/java/com/needle/FsoFso/order/controller/OrderController.java
  src/main/java/com/needle/FsoFso/order/service/OrderService.java
  src/main/java/com/needle/FsoFso/product/controller/ProductController.java
  src/main/java/com/needle/FsoFso/review/controller/ReviewController.java
  src/main/webapp/WEB-INF/spring/servlet-context.xml
  src/main/webapp/WEB-INF/views/commons/top_inc.jsp
  src/main/webapp/WEB-INF/views/error/404.jsp
  src/main/webapp/WEB-INF/views/error/error.jsp
  src/main/webapp/WEB-INF/views/layouts.xml
  src/main/webapp/WEB-INF/views/member/mypage.jsp
  src/main/webapp/WEB-INF/views/product/productDetail.jsp
  src/main/webapp/WEB-INF/web.xml
Labels: ⚒️리팩토링
